version: '3.5'

services:
  api1:
    image: vinifoliv/rinhadebackend2023
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    image: vinifoliv/rinhadebackend2023
    hostname: api2
    depends_on:
      - db
    expose:
      - "81"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./db_table.sql:/docker-entrypoint-initdb.d/db_table.sql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'