version: '3.5'

services:
  api1: &api
    image: vinifoliv/rinhadebackend2023
    hostname: api1
    ports: 
      - 80:3000
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    <<: *api
    hostname: api2
    ports:
      - 81:3000

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.2GB'

  db:
    image: postgres:17.0
    hostname: database
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./db_table.sql:/docker-entrypoint-initdb.d/db_table.sql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.8GB'